### ISSUE TITLE
Run a tiled server in the testing workflow

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#294]
Still need to run a tiled server in the testing workflow, then refactor to databroker v2.  So this PR is in draft mode ATM.

_Originally posted by @prjemian in https://github.com/bluesky/hklpy/issues/284#issuecomment-1791026416_

### Tasks
- [x] start MongoDB server - [0a20ebf](https://github.com/bluesky/hklpy/pull/295/commits/0a20ebf21313643a99dc3269f0da1d48b4bfe87c)
- [x] install database with bluesky catalogs for testing - not needed here, at least now
- [ ] Establish API key
- [x] start tiled server
- [ ] reconfigure `RE.subscribe()`
```

**Comment by prjemian** [comment]
At least two [options](https://duckduckgo.com/?q=github+action+MongoDB+server&t=brave&ia=web) for MongoDB server action:

- [mongodb-in-github-actions](https://github.com/marketplace/actions/mongodb-in-github-actions)
- [mongodb-for-github-actions](https://github.com/marketplace/actions/mongodb-for-github-actions)  - a fork from the one above

**Comment by prjemian** [comment]
Code examples from both show the same action:

```yaml
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
```

The second one has gone EOL.  So only one action now...

**Comment by prjemian** [comment]
Run [tiled server](https://github.com/bluesky/tiled/pkgs/container/tiled) in docker container.

**Comment by prjemian** [comment]
Good advice:


> Some of the examples below set an environment variable `TILED_SINGLE_USER_API_KEY` to `secret`, as a placeholder. For actual use, use a difficult-to-guess secret. Two equally good ways to generate a secure secret...
> 
> With ``openssl``:
> 
>     openssl rand -hex 32
> 
> With ``python``:
> 
>     python -c "import secrets; print(secrets.token_hex(32))"

**Comment by prjemian** [comment]
Start tiled server:

```yaml
docker run \
  -p 8000:8000 \
  -e TILED_SINGLE_USER_API_KEY=secret \
  ghcr.io/bluesky/tiled:latest
```

**Comment by prjemian** [comment]
The tests are the first items to reconfigure:

```bash
(bluesky_2023_3) prjemian@arf:~/.../Bluesky/hklpy$ git grep insert | grep subscribe
docs/source/examples/notebooks/geo_e4cv.ipynb:    "RE.subscribe(db.insert)\n",
docs/source/examples/notebooks/geo_e6c.ipynb:    "RE.subscribe(db.insert)\n",
docs/source/examples/notebooks/geo_k4cv.ipynb:    "RE.subscribe(db.insert)\n",
docs/source/examples/notebooks/tst_UB_in_descriptor_document.ipynb:    "RE.subscribe(cat.v1.insert)\n",
docs/source/examples/notebooks/tst_UB_in_stream.ipynb:    "RE.subscribe(cat.v1.insert)\n",
hkl/tests/test_save_restore_UB.py:    engine.subscribe(cat.v1.insert)
hkl/tests/test_util.py:    engine.subscribe(cat.v1.insert)
```

**Comment by prjemian** [comment]
Not necessary for PR #284.
